name: publish
on:
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"
          registry-url: https://npm.pkg.github.com/
      - run: yarn install
      - run: yarn build:all
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" > ~/.npmrc
        env: 
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      # yarn publish --access public (when package becomes public)
      - run: yarn publish:all
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
